name: Build Windows POS Client

on:
  push:
    branches: ["main", "master"]
  workflow_dispatch:

jobs:
  build-client:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          cache: true

      - name: Enable Windows Desktop
        run: flutter config --enable-windows-desktop

      - name: Build Flutter Client
        run: |
          cd pos_app
          flutter pub get
          flutter build windows

      # 只整理前端发布文件夹
      - name: Prepare Release Folder
        run: |
          mkdir POS_Client_Release
          xcopy pos_app\build\windows\x64\runner\Release\* POS_Client_Release\ /E /H /C /I

      # 上传产物
      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Windows-POS-Client
          path: POS_Client_Release/
